"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { Calendar, Mail, User } from "lucide-react";
import { Button, Card, Input, LoadingSpinner } from "@/components/ui";
import { PageHeader } from "@/components/edusphere";

type Profile = { name: string; email: string; bio: string | null; role: string; createdAt: string };

export default function ProfilePage() {
  const { status, update } = useSession(); const router = useRouter();
  const [profile, setProfile] = useState<Profile | null>(null); const [name, setName] = useState(""); const [bio, setBio] = useState(""); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { if (status === "unauthenticated") router.replace("/login"); if (status === "authenticated") fetch("/api/me").then(r => r.json()).then((data: Profile) => { setProfile(data); setName(data.name); setBio(data.bio || ""); }); }, [router, status]);
  const save = async () => { setSaving(true); setNotice(""); const response = await fetch("/api/me", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, bio }) }); const data = await response.json(); if (!response.ok) setNotice(data.error || "Impossible d'enregistrer le profil."); else { setProfile(data); setEditing(false); setNotice("Profil enregistré."); await update({ name: data.name }); } setSaving(false); };
  if (!profile) return <div className="min-h-screen grid place-items-center"><LoadingSpinner size="lg" /></div>;
  return <main className="min-h-screen bg-gradient-to-b from-slate-50 to-white"><div className="max-w-4xl mx-auto px-4 py-12"><PageHeader title="Mon profil" description="Votre identité et votre présence dans la communauté EduSphere." /><Card className="mb-8"><div className="flex flex-col sm:flex-row gap-6 items-center"><div className="w-24 h-24 shrink-0 rounded-full bg-gradient-to-br from-blue-600 to-violet-600 grid place-items-center"><User className="w-12 h-12 text-white" /></div><div className="flex-1 text-center sm:text-left"><h2 className="text-3xl font-bold">{profile.name}</h2><p className="mt-2 flex justify-center sm:justify-start gap-2 text-gray-600"><Mail className="w-4 h-4" />{profile.email}</p><span className="inline-block mt-3 px-3 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-700">{profile.role}</span></div>{!editing && <Button onClick={() => setEditing(true)}>Modifier</Button>}</div></Card>{editing ? <Card><h3 className="font-bold text-xl mb-6">Modifier mon profil</h3><div className="space-y-5"><Input label="Nom complet" value={name} maxLength={80} onChange={event => setName(event.target.value)} /><div><label className="block text-sm font-medium text-gray-700 mb-2">Bio</label><textarea value={bio} maxLength={500} onChange={event => setBio(event.target.value)} className="w-full min-h-28 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" placeholder="Présentez-vous à la communauté…" /><p className="text-right text-xs text-gray-500">{bio.length}/500</p></div><div className="flex gap-3"><Button isLoading={saving} onClick={save}>Enregistrer</Button><Button variant="secondary" onClick={() => { setEditing(false); setName(profile.name); setBio(profile.bio || ""); }}>Annuler</Button></div></div></Card> : <Card><div className="grid sm:grid-cols-2 gap-8"><div><p className="text-sm text-gray-500">Membre depuis</p><p className="font-semibold flex items-center gap-2 mt-2"><Calendar className="w-5 h-5 text-blue-600" />{new Intl.DateTimeFormat("fr-FR", { month: "long", year: "numeric" }).format(new Date(profile.createdAt))}</p></div><div><p className="text-sm text-gray-500">À propos</p><p className="font-medium mt-2 text-gray-700">{profile.bio || "Ajoutez une bio pour vous présenter aux autres apprenants."}</p></div></div></Card>}{notice && <p className={`mt-4 text-sm ${notice === "Profil enregistré." ? "text-emerald-700" : "text-red-600"}`}>{notice}</p>}</div></main>;
}
